{
  config,
  lib,
  pkgs,
  ...
}: let
  theme = import ../themes/glassbeach.nix;
  cfg = config.quickshell;

  # every flat "#rrggbb" attr of the theme, so new colours show up in QML
  # without touching this file
  colors = lib.filterAttrs (_: value: builtins.isString value && lib.hasPrefix "#" value) theme;

  colorProperties =
    lib.concatStringsSep "\n"
    (lib.mapAttrsToList (name: value: "    readonly property color ${name}: \"${value}\";") colors);

  themeQml = pkgs.writeText "Theme.qml" ''
    pragma Singleton
    import QtQuick
    import Quickshell

    // Generated from modules/themes/glassbeach.nix -- edit that, not this.
    Singleton {
    ${colorProperties}

        readonly property string fontFamily: ${builtins.toJSON cfg.fontFamily};
    }
  '';

  configQml = pkgs.writeText "Config.qml" ''
    pragma Singleton
    import QtQuick
    import Quickshell

    // Generated from modules/quickshell/quickshell.nix -- edit that, not this.
    Singleton {
        readonly property string monitor: ${builtins.toJSON cfg.monitor};

        readonly property QtObject volume: QtObject {
            readonly property bool onRight: ${lib.boolToString (cfg.volume.edge == "right")};
            readonly property int collapsedWidth: ${toString cfg.volume.collapsedWidth};
            readonly property int expandedWidth: ${toString cfg.volume.expandedWidth};
            readonly property int bandHeight: ${toString cfg.volume.bandHeight};
            readonly property real step: ${toString cfg.volume.step};
            readonly property bool handle: ${lib.boolToString cfg.volume.handle};
        }
    }
  '';

  # the hand-written QML is symlinked back to the working tree instead of the
  # store, so edits hot-reload without a rebuild
  source = "${config.home.homeDirectory}/nixos-config/modules/quickshell";
  liveLink = path: config.lib.file.mkOutOfStoreSymlink "${source}/${path}";
in {
  options.quickshell = {
    enable = lib.mkEnableOption "the quickshell desktop widgets";

    monitor = lib.mkOption {
      type = lib.types.str;
      default = "";
      example = "eDP-1";
      description = "Output to place the widgets on. Empty means every output.";
    };

    fontFamily = lib.mkOption {
      type = lib.types.str;
      default = "GoMono Nerd Font";
      description = "Font used by the widgets, needs the nerd font glyphs.";
    };

    volume = {
      edge = lib.mkOption {
        type = lib.types.enum ["left" "right"];
        default = "left";
        description = "Screen edge the slider hides against.";
      };

      collapsedWidth = lib.mkOption {
        type = lib.types.int;
        default = 6;
        description = "Width of the hover strip while the slider is closed.";
      };

      expandedWidth = lib.mkOption {
        type = lib.types.int;
        default = 54;
        description = "Width of the slider once it opens.";
      };

      bandHeight = lib.mkOption {
        type = lib.types.int;
        default = 300;
        description = "Height of the hover band, centred on the screen edge.";
      };

      step = lib.mkOption {
        type = lib.types.float;
        default = 0.02;
        description = "Volume change per scroll notch, 0.0 to 1.0.";
      };

      handle = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Show a sliver on the edge hinting the slider is there.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [pkgs.quickshell];

    xdg.configFile = {
      # generated by nix, replaced on rebuild
      "quickshell/Theme.qml".source = themeQml;
      "quickshell/Config.qml".source = configQml;

      # hand-written, editable in place
      "quickshell/shell.qml".source = liveLink "shell.qml";
      "quickshell/services".source = liveLink "services";
      "quickshell/widgets".source = liveLink "widgets";
    };

    systemd.user.services.quickshell = {
      Unit = {
        Description = "Quickshell desktop widgets";
        Documentation = "https://quickshell.org";
        PartOf = ["graphical-session.target"];
        After = ["graphical-session.target"];
        ConditionEnvironment = "WAYLAND_DISPLAY";
        # restart when the generated singletons change; the live-linked QML
        # hot-reloads on its own
        X-GeneratedConfig = "${themeQml} ${configQml}";
      };

      Service = {
        ExecStart = "${pkgs.quickshell}/bin/qs -c default";
        Restart = "on-failure";
        Slice = "session.slice";
      };

      Install.WantedBy = ["graphical-session.target"];
    };
  };
}
