-- `nix` (~/.config/hypr/nix.lua) is generated by hyprland.nix and carries
-- the scripts path, theme colours and per-host monitors.

require("modules.env")
require("modules.monitors")
require("modules.autostart")
require("modules.input")
require("modules.layout")
require("modules.lnf_decorations")
require("modules.lnf_animations")
require("modules.windowrules")
require("modules.misc")
require("modules.binds")
